### ISSUE TITLE
Network Unreachable bug

### ISSUE THREAD

**Issue by IgorKurylev** [Usvel/ParanoidVpnApp#15]
При запуске LocalVpnService без наличия сети вылетает Network is unreachable exception (нужно подождать некоторое время)

- Исключение, которое, на мой взгляд, является причиной

```
2021-10-28 13:46:07.205 25765-25791/com.example.paranoid E/BioUdpHandler: error
    java.net.ConnectException: Network is unreachable
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:465)
        at sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:775)
        at com.example.paranoid.ui.vpn.basic_client.bio.BioUdpHandler.run(BioUdpHandler.java:177)
        at com.example.paranoid.ui.vpn.basic_client.LocalVPNService2$onCreate$1.invokeSuspend(LocalVPNService2.kt:55)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

- Еще одно исключение, которое вылетает

```
2021-10-28 13:46:05.122 25765-25765/com.example.paranoid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.paranoid, PID: 25765
    java.lang.RuntimeException: Unable to start service com.example.paranoid.ui.vpn.basic_client.LocalVPNService2@ab3f4fb with null: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter intent
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3696)
        at android.app.ActivityThread.-wrap21(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter intent
        at com.example.paranoid.ui.vpn.basic_client.LocalVPNService2.onStartCommand(Unknown Source:2)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3679)
        at android.app.ActivityThread.-wrap21(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944)
```

**Comment by IgorKurylev** [comment]
В *BioUdpHandler* в обработчике исключения вызывался *exitProcess*, который клал все приложение:
 
```kotlin
try {
    ...
} catch (e: Exception) {
    Log.e(TAG, "error", e)
    exitProcess(0)
}
```
